- alias: 'covid wakeup lights'
  trigger:
    - platform: time
      at: '06:00:00'

  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

  action:
    - service: light.turn_on
      entity_id: light.master_closet_anne
    - service: cover.open_cover
      entity_id: 
      - cover.master_blinds_1
      - cover.office_blinds