# Turn on outdoor lights at sunset, turn off at 10:30pm

#Turn outdoor lights on 30 minutes before sunset
- alias: 'turn outdoor lights on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.outside_front_flood
        - switch.outside_back_flood
    - service: light.turn_on
      entity_id:
        - light.outside_front_stoop
  


# Turn outdoor lights off at 11:00 pm      
- alias: 'turn outdoor lights off'
  trigger:
    - platform: time
      at: '23:00:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.outside_front_flood
        - switch.outside_back_flood
    - service: light.turn_off
      entity_id:
        - light.outside_front_stoop

# Lower Shades 30 minutes after sunset
- alias: 'Lower evening shades'
  trigger:
    - platform: sun
      event: sunset
      offset: '00:30:00'
  action:
    - service: cover.close_cover
      entity_id:
        - group.all_den_blinds
        - group.all_master_blinds
        - group.all_office_blinds