- alias: "Good Morning Routine 2"
  trigger:
  - platform: state
    entity_id: input_boolean.good_morning_trigger
    from: 'off'
    to: 'on'

  action:
  - service: scene.turn_on
    entity_id: scene.good_morning_scene

  - delay: 120

  - service: input_boolean.turn_off
    entity_id: input_boolean.good_morning_trigger