- alias: Water Closet Fan & Light turn off
  trigger: 
    - platform: state
      entity_id: binary_sensor.master_toilet
      to: 'off'
      from: 'on'

  action:
    - service: light.turn_off
      entity_id: light.toilet_lights
    - delay: '00:10:00'
    - service: switch.turn_off
      entity_id: switch.master_bath_fan