esphome:
  name: annes_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "ESP8266_IOT"
  password: "abcd1234"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Anne's Lamp"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Anne's Lamp"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: wifi_signal
    name: "Annes's Lamp WiFi signal"
    update_interval: 120s

  - platform: uptime
    name: "Annes's Lamp uptime"

text_sensor:
  - platform: version
    name: "Annes's Lamp ESPHome version"