esphome:
  name: drews_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Drew's Lamp"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Drew's Lamp"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: wifi_signal
    name: "Drew's Lamp WiFi signal"
    update_interval: 120s

  - platform: uptime
    name: "Drew's Lamp uptime"

text_sensor:
  - platform: version
    name: "Drew's Lamp ESPHome version"